### ISSUE TITLE
Hiding Commands Section

### ISSUE THREAD

**Issue by vsnthdev** [ahmadawais/cli-meow-help#1]
I am making a CLI program where there's only one `root` command. So, how do I hide the empty commands section? 🤔 Here's a picture of the empty commands section, I would like to hide 👇
![Screenshot 2020-11-07 at 2 11 54 PM](https://user-images.githubusercontent.com/24322511/98436674-3e5f8d00-2103-11eb-9c52-6574e58fbac8.png)

**Comment by vsnthdev** [comment]
I'm closing this issue since package isn't maintained anymore.

**Comment by corysimmons** [comment]
@ahmadawais Pleas re-open/fix this. Basically don't render _any_ sections that are falsy.

This includes the `USAGE` string (don't render `<command>` or `[option]` if they don't exist.

**Comment by ahmadawais** [comment]
I'd accept a PR for this. Thank you! 🙌

**Comment by corysimmons** [comment]
@ahmadawais https://github.com/ahmadawais/cli-meow-help/pull/2
